---
- hosts: all
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: 'install python'
    raw: 'apt-get -y install python'

- hosts: teste
  become: yes 
  user: ubuntu 
  roles: 
  - common_setup 
  tags: common

- hosts: teste
  become: yes 
  user: ubuntu 
  roles: 
  - create-cluster
  tags: master 

- hosts: workers
  become: yes
  user: ubuntu 
  roles: 
  - common_setup
  - workers 
  tags: workers 
