---
# handlers file for common_setup
- name: daemon-reload
  command: systemctl daemon-reload 
  
- name: enable docker
  service: name=docker enabled=yes

- name: restart docker
  service: name=docker state=restarted
