- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: sysctl -p disabling IPv6 
  shell:  sysctl -p

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable SWAP in fstab 
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Template /usr/local/bin/check-update.sh
  template:
    src: ../templates/check-update.sh
    dest: /usr/local/bin/check-update.sh
    owner: root
    group: root
    mode: '0755'

- name: Running /usr/local/bin/check-update.sh
  shell: sh /usr/local/bin/check-update.sh 

- name: Template a file to /etc/modules-load.d/k8s.conf
  template:
    src: ../templates/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0755'

- name: Check if docker it's already installed and running
  command: systemctl status docker.service
  register: docker_status
  failed_when: docker_status.rc > 3

- name: Install docker
  shell: curl -fsSL https://get.docker.com | bash
  when: "'running' not in docker_status.stdout"

- name: Creating /etc/docker
  file:
    path: /etc/docker
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Check if /etc/docker/daemon.json exists
  stat:
    path: /etc/docker/daemon.json
  register: daemon_json

- name: Changing daemon of docker to systemd 
  template:
    src: ../templates/daemon.json 
    dest: /etc/docker/daemon.json 
    owner: root
    group: root
    mode: '0755'
  when: daemon_json.stat.exists == False 
  notify: 
  - daemon-reload
  - restart docker 

- name: Creating /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes
    owner: root 
    group: root

- name: Install pre-requires 
  apt: 
    pkg:
    - apt-transport-https 
    - gnupg2  

- name: Add Apt signing key for k8s 
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install k8s packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
    - bash-completion 
